services:
  web:
    build: ./docker/php
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.4
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    restart: unless-stopped

volumes:
  mysql_data: