services:
  web:
    build: ./docker/php
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.4
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
